[project]
name = "cog"
readme = "README.md"
requires-python = ">=3.6.0"

[tool.poetry]
name = "cog"
description = "Containers for machine learning"
version = "0.0.1"
license = "Apache License 2.0"
authors = [
    "Replicate Team <team@replicate.com>",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
